services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "'db.runCommand({ping:1})'"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  crud:
    image: ghcr.io/mmi-s4/exemple_crud:main
    build: ./src
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_DATABASE=mmidb
    networks:
      - nginx
      - mongo
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy

  nginx:
    image: nginx
    ports:
      - 80:80
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/crud.conf
    networks:
      - nginx
    depends_on:
      - crud
    restart: unless-stopped
configs:
  nginx-config:
    file: ./nginx/crud.conf

networks:
  nginx:
  mongo: