services:
  mongodb:
    image: mongo
    volumes:
      - ./mongodb:/data/db
    networks:
      - mongo
  
  crud:
    image: ghcr.io/mmi-s4/exemple_crud:main
    build: ./src
    environment:
      - MONGO_SERVER=mongodb
      - MONGO_DATABASE=mmidb
    networks:
      - nginx
      - mongo
    depends_on:
      - mongodb

  nginx:
    image: nginx
    ports:
      - 80:80
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/crud.conf
    networks:
      - nginx
    depends_on:
      - crud

configs:
  nginx-config:
    file: ./nginx/crud.conf

networks:
  nginx:
  mongo: